version: '3.4'

services:
  library-app-api:
    image: library-app-api
    container_name: library-app-api
    build:
      context: ./LibraryApp.WebApi
      dockerfile: Dockerfile
    ports:
      - "8980:80"
    networks:
      - mynetwork
  libraryappsqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: libraryappsqlserver
    ports:
      - "14330:1433"
    environment:
      - SA_PASSWORD=Abc.123456
      - ACCEPT_EULA=Y
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge